import { StyleSheet } from "react-native";

const style = StyleSheet.create({
    body:{
        backgroundColor:"#1A1A1B",
        width:"100%",
        height:"100%"
    },
    btnWithout:{
        alignSelf:"flex-end",
        marginTop:-50,
        marginRight:15,
        margin:15
    },
    textTop:{
        color:"#cccccc",
        margin:15,
        fontSize:15,
        fontWeight:"bold",   
        alignSelf:"flex-end"
    },
    container2:{
       width:20,
       height:20,
       marginLeft:7,
       marginBottom:"3%"
    },
    container1:{
        width:"100%",
        height:100,
        marginTop:"20%"
    },
    container:{
        width:50,
        height:50,
        alignSelf:"center",
    },
    map:{
        width:"98%",
        height:250,
        alignSelf:"center"
    },
    nomeUser:{
        color:"#8D8D99",
        fontSize:15
    },
    imgUser:{
        width:50,
        height:50,
        marginRight:10
    },
    container3:{
        flexDirection:"row",
        marginLeft:20
    },
    matricula:{
       fontSize:18,
       color:"#cccccc"
    },
    textMain:{
        color:"#8D8D99",
        fontSize:14,
        alignSelf:"center",
        marginTop:"75%"
    }
    });
    export default style;